<?php

namespace Sebastienheyd\Boilerplate\Dashboard;

class DashboardWidgetsRepository
{
    protected $widgets = [];

    public function __construct()
    {
        $this->getProviders();
    }

    /**
     * Register one or more widget classes.
     *
     * @param  ...$class
     * @return $this
     *
     * @throws ReflectionException
     */
    public function registerWidget(...$class)
    {
        foreach ($class as $c) {
            if (! is_subclass_of($c, Widget::class)) {
                continue;
            }

            $widget = new $c;

            $this->widgets[$widget->slug] = $widget;
        }

        return $this;
    }

    /**
     * Get an array of the registered widgets.
     *
     * @return Widget[]
     */
    public function getWidgets()
    {
        return $this->widgets;
    }

    /**
     * Get the widget with the given slug.
     *
     * @param  string  $slug
     * @return Widget|false
     */
    public function getWidget($slug)
    {
        return $this->widgets[$slug] ?? false;
    }

    /**
     * Register the widgets generated by the Artisan command.
     *
     * @return void
     */
    private function getProviders()
    {
        if (! is_dir(app_path('Dashboard'))) {
            return;
        }

        $classes = glob(app_path('Dashboard').'/*.php');

        if (empty($classes)) {
            return;
        }

        foreach ($classes as $class) {
            $this->registerWidget('\\App\\Dashboard\\'.preg_replace('#\.php$#i', '', basename($class)));
        }
    }
}
