name: Build and Deploy Docs
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: docs/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: docs

      - name: Build
        run: yarn docs:build
        working-directory: docs

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/.vuepress/dist
